export type MockOpportunity = {
  id: string;
  tmdbMovieId?: number;
  tmdbTitle?: string;
  category: string;
  title: string;
  shortTitle: string;
  description: string;
  score: string;
  signal: "Peak" | "Rising" | "Emerging";
  image: string;
  imageAlt: string;
  source: string;
  published: string;
  trend: string;
  volume: string;
  window: string;
  why: string;
  angles: string[];
  titles: string[];
};

export const mockOpportunities: MockOpportunity[] = [
  {
    id: "sequel-anxiety",
    category: "Cultural anxiety",
    title: "The 2000s sequel anxiety",
    shortTitle: "Sequel anxiety",
    description: "Studios are greenlighting 14 franchise continuations this quarter. Audiences are caught between nostalgia and exhaustion.",
    score: "9.2",
    signal: "Peak",
    image: "/images/lead-cinema.png",
    imageAlt: "A woman in a red coat outside a weathered cinema",
    source: "Industry press monitor",
    published: "Today, 04:12 GMT",
    trend: "+340%",
    volume: "2.4M searches / day",
    window: "3-day peak",
    why: "Audience discourse has shifted from anticipation to exhaustion in under 60 days. That creates a rare opening where critical analysis is dramatically outperforming hype coverage, especially when it connects sequel fatigue to the economics of original filmmaking.",
    angles: ["Why we keep getting nostalgia sequels completely wrong", "The ten properties that deserve a second chance", "How sequel saturation is quietly funding original filmmaking"],
    titles: ["Nostalgia Has a Sequel Problem", "The Franchise Hangover Is Here", "Why Hollywood Cannot Leave the 2000s Alone"],
  },
  {
    id: "quiet-film-paradox",
    tmdbMovieId: 916405,
    tmdbTitle: "The Quiet Girl",
    category: "Streaming economics",
    title: "The quiet film paradox",
    shortTitle: "Quiet film paradox",
    description: "Minimalist films are outperforming tent-poles on per-screen average by four times.",
    score: "8.1",
    signal: "Rising",
    image: "/images/quiet-cinema.png",
    imageAlt: "A solitary audience member in an empty cinema",
    source: "Exhibition data brief",
    published: "Today, 05:44 GMT",
    trend: "+112%",
    volume: "680K searches / day",
    window: "7-day window",
    why: "A cluster of quiet, formally restrained films is holding screens longer than expected. The useful story is not that audiences have rejected spectacle, but that attention is fragmenting into smaller and more committed cultural publics.",
    angles: ["Why audiences are craving screen silence", "The algorithm finally rewards what film school taught", "What a strong per-screen average actually reveals"],
    titles: ["The Films Winning by Whispering", "Quiet Cinema, Loud Results", "The Box Office Has a Volume Problem"],
  },
  {
    id: "practical-effects-renaissance",
    tmdbMovieId: 872585,
    tmdbTitle: "Oppenheimer",
    category: "Craft & production",
    title: "Practical effects renaissance",
    shortTitle: "Practical effects",
    description: "Behind-the-scenes footage of handcrafted SFX is outpacing the films themselves.",
    score: "7.8",
    signal: "Rising",
    image: "/images/practical-effects.png",
    imageAlt: "A craftsperson lighting a miniature film set",
    source: "Official video monitor",
    published: "Today, 06:00 GMT",
    trend: "+89%",
    volume: "540K views / day",
    window: "10-day window",
    why: "Process footage is giving audiences a tangible way into film craft. The strongest opportunity is to move beyond the usual practical-versus-digital argument and show how the two practices now depend on one another.",
    angles: ["The death and rebirth of movie magic", "Why AI did not kill practical effects", "The miniature makers becoming stars"],
    titles: ["Movie Magic Has Hands Again", "Inside the Return of the Miniature", "Practical Effects Never Really Left"],
  },
  {
    id: "female-debut-directors",
    tmdbMovieId: 666277,
    tmdbTitle: "Past Lives",
    category: "Industry shift",
    title: "Female debut directors at box office",
    shortTitle: "Debut directors",
    description: "Three top-ten global films this summer are debut features by women.",
    score: "7.4",
    signal: "Emerging",
    image: "/images/debut-directors.png",
    imageAlt: "Three film directors crossing a studio soundstage",
    source: "Global box office report",
    published: "Today, 07:15 GMT",
    trend: "+67%",
    volume: "320K searches / day",
    window: "2-week window",
    why: "The immediate result is striking, but the deeper story sits in the financing and festival pipelines that made these debuts possible. Treating the pattern as an industry system rather than a novelty will produce the more durable piece.",
    angles: ["What changed in Hollywood financing", "The overlooked festivals that predicted this wave", "Why debut films are becoming safer bets"],
    titles: ["The Debut Directors Rewriting the Top Ten", "A New First-Film Economy", "Hollywood's Most Interesting Directors Are Arriving Early"],
  },
  {
    id: "imax-reissue-economy",
    tmdbMovieId: 157336,
    tmdbTitle: "Interstellar",
    category: "Exhibition",
    title: "The IMAX reissue economy",
    shortTitle: "IMAX reissue economy",
    description: "Large-format reissues are turning repertory screenings into appointment-viewing events.",
    score: "8.3",
    signal: "Rising",
    image: "/images/lead-cinema.png",
    imageAlt: "A woman in a red coat outside a weathered cinema",
    source: "Source placeholder: exhibitor booking report",
    published: "Today, 08:05 GMT",
    trend: "+146%",
    volume: "910K searches / day",
    window: "5-day window",
    why: "Premium-format reissues are behaving less like catalogue programming and more like new releases. That shift gives creators a timely way to examine how scarcity, scale, and collective viewing are rebuilding the value of films audiences can already watch at home.",
    angles: ["Why old films are selling out the biggest screens", "The new economics of event reissues", "How scarcity turned repertory cinema into a launch strategy"],
    titles: ["The Blockbuster Is Back, Again", "Why Reissues Feel Like Premieres Now", "The Big-Screen Second Life"],
  },
  {
    id: "animation-handmade-digital-turn",
    tmdbMovieId: 569094,
    tmdbTitle: "Spider-Man: Across the Spider-Verse",
    category: "Craft & production",
    title: "Animation's handmade digital turn",
    shortTitle: "Handmade digital animation",
    description: "Visible brushwork and mixed-media textures are becoming the new mark of premium animation.",
    score: "8.0",
    signal: "Rising",
    image: "/images/practical-effects.png",
    imageAlt: "A craftsperson lighting a miniature film set",
    source: "Source placeholder: animation craft monitor",
    published: "Today, 08:42 GMT",
    trend: "+104%",
    volume: "760K views / day",
    window: "8-day window",
    why: "Audiences are responding to digital animation that foregrounds evidence of the artist's hand. The opportunity is to explain the production systems behind that look and why controlled imperfection now signals ambition rather than roughness.",
    angles: ["Why polished animation is learning to look unfinished", "The artists behind cinema's new visual texture", "How mixed media escaped the experimental short"],
    titles: ["Animation Leaves the Clean Line Behind", "The Handmade Future of Digital Film", "Perfect Pictures Are Losing Their Appeal"],
  },
  {
    id: "mid-budget-horror-advantage",
    tmdbMovieId: 933260,
    tmdbTitle: "The Substance",
    category: "Cultural anxiety",
    title: "The mid-budget horror advantage",
    shortTitle: "Mid-budget horror",
    description: "Body horror is carrying star-driven social satire back into the theatrical conversation.",
    score: "8.5",
    signal: "Peak",
    image: "/images/quiet-cinema.png",
    imageAlt: "A solitary audience member in an empty cinema",
    source: "Source placeholder: genre performance brief",
    published: "Today, 09:10 GMT",
    trend: "+188%",
    volume: "1.1M searches / day",
    window: "4-day peak",
    why: "A new cycle of horror is combining legible cultural anxieties with the visual confidence of prestige filmmaking. Its modest budgets leave room for formal risk, while strong imagery gives critics and video essayists unusually durable material.",
    angles: ["Why horror became the home of the mid-budget star vehicle", "The beauty economy's most revealing monster", "How practical gore became prestige imagery"],
    titles: ["Horror Inherited the Mid-Budget Movie", "The Monster in the Mirror", "Prestige Cinema Gets Its Hands Dirty"],
  },
  {
    id: "subtitles-mainstream-signal",
    tmdbMovieId: 496243,
    tmdbTitle: "Parasite",
    category: "Industry shift",
    title: "Subtitles become a mainstream signal",
    shortTitle: "Mainstream subtitles",
    description: "International-language hits are reshaping how distributors package discovery for broad audiences.",
    score: "7.9",
    signal: "Rising",
    image: "/images/lead-cinema.png",
    imageAlt: "A woman in a red coat outside a weathered cinema",
    source: "Source placeholder: international distribution brief",
    published: "Today, 09:36 GMT",
    trend: "+96%",
    volume: "630K searches / day",
    window: "12-day window",
    why: "Subtitles are increasingly framed as evidence of cultural access rather than a barrier to entry. The stronger story is how distributors, exhibitors, and platforms learned to sell specificity without flattening it into a generic global-content label.",
    angles: ["How distributors stopped apologizing for subtitles", "The campaign language that made specificity travel", "What the global hit means after awards season ends"],
    titles: ["The Subtitle Barrier Was a Marketing Problem", "How Specific Films Became Global Events", "Cinema's New Common Language"],
  },
  {
    id: "first-feature-prestige-pipeline",
    tmdbMovieId: 965150,
    tmdbTitle: "Aftersun",
    category: "Industry shift",
    title: "The first-feature prestige pipeline",
    shortTitle: "First-feature pipeline",
    description: "Debut filmmakers are reaching prestige audiences through a tighter festival-to-streaming path.",
    score: "7.6",
    signal: "Emerging",
    image: "/images/debut-directors.png",
    imageAlt: "Three film directors crossing a studio soundstage",
    source: "Source placeholder: festival acquisition tracker",
    published: "Today, 10:02 GMT",
    trend: "+72%",
    volume: "410K searches / day",
    window: "2-week window",
    why: "The path from festival discovery to long-tail audience attention is becoming more legible for first-time filmmakers. Mapping that path can reveal which institutions still create meaningful cultural momentum after the premiere headlines fade.",
    angles: ["The festivals that make a debut travel", "Why first features now have a longer cultural life", "Inside the new prestige discovery pipeline"],
    titles: ["The First Film Is No Longer a Calling Card", "How Debuts Find Their Second Audience", "From Festival Whisper to Cultural Reference"],
  },
  {
    id: "maximalist-indie-afterlife",
    tmdbMovieId: 545611,
    tmdbTitle: "Everything Everywhere All at Once",
    category: "Craft & production",
    title: "The maximalist indie afterlife",
    shortTitle: "Maximalist indie afterlife",
    description: "Small production teams are turning visual excess into a repeatable independent-film language.",
    score: "7.7",
    signal: "Emerging",
    image: "/images/practical-effects.png",
    imageAlt: "A craftsperson lighting a miniature film set",
    source: "Source placeholder: independent production survey",
    published: "Today, 10:28 GMT",
    trend: "+81%",
    volume: "470K views / day",
    window: "10-day window",
    why: "The visual density once associated with studio-scale effects is now achievable through small, highly integrated teams. The useful opportunity is to examine the labor, planning, and taste that make maximalism coherent on an independent budget.",
    angles: ["How tiny effects teams learned to build multiverses", "Why maximalism is an indie production strategy", "The invisible planning behind visual chaos"],
    titles: ["The Indie Film Learned to Go Big", "Maximum Cinema, Minimum Crew", "How Small Teams Built a Bigger Screen"],
  },
];

export function getOpportunity(id: string) {
  return mockOpportunities.find((item) => item.id === id);
}
